# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy to Somee via FTP

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'  # adjust to your .NET version

    - name: Enable Corepack (for Yarn)
      run: corepack enable

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'yarn'

    - name: Install compatible @types/node version
      run: yarn add -D @types/node@20.11.0  

    - name: Install Front-End Dependencies
      working-directory: tictactoe.client  # adjust to your actual client path
      run: yarn install

    - name: Publish .NET App
      run: dotnet publish ./TicTacToe.Server/TicTacToe.Server.csproj -c Release -o published

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        port: 21
        local-dir: ./published/
        server-dir: /www.tictactoe.somee.com/
